davide_ubuntu:
  hosts:
    hilwdweu220401a.datawarehouse.expecn.com:
    ashldweu2201a.karmalab.net:
      ansible_python_interpreter: /usr/bin/python3

davide_rhel:
  hosts:
    ashldweora801b.karmalab.net:
      ansible_python_interpreter: /usr/bin/python3

davide:
  children:
    davide_ubuntu:
    davide_rhel:
