all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ (lookup('pipe','uname -s').strip() == 'Darwin') | ternary(lookup('env','HOME') ~ '/.pyenv/shims/python3', '/usr/bin/python3') }}"
