---

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false

- name: Ensure aptitude is installed
  ansible.builtin.apt:
    name: aptitude
    state: present

# This step does "apt-get dist-upgrade" which does a full update of installed packages.
- name: Debian Upgrade all
  ansible.builtin.apt:
    upgrade: dist
    autoclean: true
    autoremove: true
