---

- name: Include tasks for docker on Debian/Ubuntu
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family == 'Debian'

- name: Include tasks for docker on RedHat/CentOS
  ansible.builtin.include_tasks: redhat.yaml
  when: ansible_os_family == 'RedHat'
